# Generated by Django 5.1.3 on 2024-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('canceled', 'Cancelada')], default='pending', max_length=10),
        ),
    ]
